# Welcome to Jekyll!
#

# Site settings
title: Maria Ascolese
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Maria Ascolese
first_published: 2024
email: ascolese.datascience@gmail.com
baseurl: ""
url: "http://yourdomain.com"
social:
  github: https://github.com/maria-ascolese
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  email: ascolese.datascience@gmail.com
  #flickr:
  instagram: https://instagram.com/mariaasx
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
